### ISSUE TITLE
実行計画ファイルに対応する

### ISSUE THREAD

**Issue by sasano8** [sasano8/asy#2]
１クラスを１つのデーモンとして扱うことしかできないので、複数のデーモンを実行できるようにする。

``` yaml
wokers:
  sync_parelle: 2  # 実行プロセス数
  async_parelle: 2  # 非同期並列数

  deamons:
    example.class1:
      envs:
        max: 5
    example.class2:
      envs:
        max: 3
```

``` shell
asy --config=example.yaml
```
